#!/bin/bash

ConfigureNewWorld() {
    cp -r res/sample_worlds/$2/ configs/$1/
    echo New world saved at configs/$1/
}

if [ $# -eq 1 ] && [[ "$1" == "--help" || "$1" == "-h" ]] || [ $# -eq 0 ]; then

    cat res/ascii_art.txt
    cat res/help_page.txt

elif [[ $# -eq 3 && "$1" == "new-world" ]]; then

    if [ -d "configs/$2/" ]; then
        echo "Error: A world named $2 already exists"
        exit 1
    elif [ ! -d "res/sample_worlds/$3/" ]; then
        echo "Error: Could not find sample world named $3"
        exit 1
    else
        ConfigureNewWorld $2 $3
    fi

elif [[ $# -eq 2 && "$1" == "generate-and-render" ]]; then

    nargen generate $2 && nargen render-game $2

elif [[ $# -eq 2 && "$1" == "generate" ]]; then

    if [ $# -lt 2 ]; then
        echo "Invalid arguments: No config file specified"
        cat res/help_page.txt
    elif [ -d "configs/$2/" ]; then
        cat configs/$2/CONFIG.json
        rm -r -f worlds/$2/
        if [ $# -ge 3 ]; then
            if [ $3 == "--no-rendering" ]; then
                python3 main.py generate $2 0
            else
                echo "Invalid arguments: Cannot recognise option $3"
                cat res/help_page.txt
            fi
        else
            python3 main.py generate $2 1
        fi

    else
        echo "Error: Cannot find world named $2"
        exit 1
    fi

elif [[ $# -ge 1 && "$1" == "delete-world" ]]; then

    if [ $# -lt 2 ]; then
        echo "Invalid arguments: No world name specified"
        cat res/help_page.txt
    elif [ -d "configs/$2" ]; then
        rm -r -f configs/$2
        echo "Deleted world $2"
    else
        echo "Error: Cannot find world named $2"
        exit 1
    fi

elif [[ $# -eq 2 && "$1" == "render" ]]; then

    if [ -d "worlds/$2/" ]; then
        if [ -f "worlds/$2/WORLD_INFO.json" ]; then
            python3 main.py render $2
        else
            echo "Error: A world named $2 is found but is not fully rendered. Execute 'nargen generate $2' to generate the world."
            exit 1
        fi
    else
        echo "Error: No world named $2 has been generated. Execute 'nargen generate $2' to generate the world."
        exit 1
    fi

elif [[ $# -eq 2 && "$1" == "build" ]]; then

    nargen generate $2 && nargen render-game $2

elif [[ $# -eq 2 && "$1" == "render-game" ]]; then

    if [ -d "worlds/$2/" ]; then
        if [ -f "worlds/$2/WORLD_INFO.json" ]; then
            python3 main.py render-game $2
            viewnior worlds/$2/images/game.png > /dev/null 2>&1
        else
            echo "Error: A world named $2 is found but is not fully rendered. Execute 'nargen generate $2' to generate the world."
        fi
    else
        echo "Error: Cannot find world named $2. Execute 'nargen generate $2' to generate the world."
        exit 1
    fi

elif [[ $# -eq 2 && "$1" == "view" ]]; then

    if [ -d "worlds/$2/" ]; then
        viewnior worlds/$2/images/ > /dev/null 2>&1
    elif [ -d "configs/$2/" ]; then
        echo "Error: $2 has not yet been generated"
        nargen generate $2
    else
        echo "Error: Cannot find world named $2."
        exit 1
    fi

elif [[ $# -eq 1 && "$1" == "list" ]]; then

    ls configs/

elif [[ $# -eq 1 && "$1" == "list-sample-worlds" ]]; then

    ls res/sample_worlds/

elif [[ $# -eq 1 && "$1" == "install" ]]; then

    mkdir worlds/

else

    echo "Invalid arguments"
    cat res/help_page.txt

fi
