#!/bin/bash

ConfigureNewWorld() {
    WORLD_PATH=$1
    SAMPLE_WORLD_NAME=$2
    cp -r $NARGEN_PATH/res/sample_worlds/$SAMPLE_WORLD_NAME $WORLD_PATH
    mkdir -p \
        $WORLD_PATH/GENERATED/chunks/ \
        $WORLD_PATH/GENERATED/images/
    echo New world saved at $WORLD_PATH
}

AssureWorldExists() {
    WORLD_PATH=$1
    if [ ! -d "$WORLD_PATH" ]; then
        echo "Error: Cannot find world at $WORLD_PATH"
        exit 1
    fi
}

DeleteTerrain() {
    WORLD_PATH=$1
    rm -rf $WORLD_PATH/GENERATED/*
    mkdir $WORLD_PATH/GENERATED/chunks/ $WORLD_PATH/GENERATED/images/
}

Render() {
    WORLD_PATH=$1
    python3 main.py render $WORLD_PATH
    ViewWorld $WORLD_PATH
}

ViewWorld() {
    WORLD_PATH=$1
    xdg-open $WORLD_PATH/GENERATED/images/* > /dev/null 2>&1
}

if [ $# -eq 1 ] && [[ "$1" == "--help" || "$1" == "-h" ]] || [ $# -eq 0 ]; then

    cat res/ascii_art.txt
    cat res/help_page.txt

elif [[ $# -eq 3 && "$1" == "new-world" ]]; then

    WORLD_PATH=$2
    SAMPLE_WORLD_NAME=$3

    [ -d "$WORLD_PATH" ] && echo "Error: A world already exists at $WORLD_PATH" && exit 1
    [ ! -d "$NARGEN_PATH/res/sample_worlds/$SAMPLE_WORLD_NAME/" ] && echo "Error: Could not find sample world named $SAMPLE_WORLD_NAME" && exit 1

    ConfigureNewWorld $WORLD_PATH $SAMPLE_WORLD_NAME

elif [[ $# -eq 2 && "$1" == "generate" ]]; then

    WORLD_PATH=$2

    AssureWorldExists $WORLD_PATH

    DeleteTerrain $WORLD_PATH

    node main.js generate $WORLD_PATH 1

elif [[ $# -eq 2 && "$1" == "delete-terrain" ]]; then

    WORLD_PATH=$2

    AssureWorldExists $WORLD_PATH

    DeleteTerrain $WORLD_PATH

    echo "Emptied world at $WORLD_PATH"

elif [[ $# -eq 2 && "$1" == "render" ]]; then

    WORLD_PATH=$2

    AssureWorldExists $WORLD_PATH

    if [ -f "$WORLD_PATH/GENERATED/WORLD_INFO.json" ]; then
        Render $WORLD_PATH
    else
        echo "Error: A world at $WORLD_PATH is found but is not fully rendered. Execute 'nargen generate $WORLD_PATH' to generate the world."
    fi

elif [[ $# -eq 2 && "$1" == "view" ]]; then

    WORLD_PATH=$2

    AssureWorldExists $WORLD_PATH

    ViewWorld $WORLD_PATH

elif [[ $# -eq 1 && "$1" == "list-sample-worlds" ]]; then

    ls $NARGEN_PATH/res/sample_worlds/

else

    echo "Invalid arguments"
    cat $NARGEN_PATH/res/help_page.txt

fi
