#!/bin/bash

#ffmpeg -framerate 10 -pattern_type glob -i ./TREE_3/%d.png output.mp4

#ffmpeg -framerate 30 -pattern_type glob -i TREE_3/%d.png \
  #-c:v libx264 -pix_fmt yuv420p out.mp4

ffmpeg -framerate 20 -i $1/%d.png \
    -c:v libx264 -pix_fmt yuv420p output.mp4
