#!/bin/bash

# This script bundles NarGen into a script for use in a browser

WEB_VERSION_FILEPATH=/home/jack/Web-Dev/nargen-web

rm -rf $WEB_VERSION_FILEPATH/src/scripts/*

mkdir $WEB_VERSION_FILEPATH/src/scripts/lib/

cp src/lib/alea.js $WEB_VERSION_FILEPATH/src/scripts/lib/alea.js
cp src/BiomeBlender.js $WEB_VERSION_FILEPATH/src/scripts/BiomeBlender.js
cp src/Biome.js $WEB_VERSION_FILEPATH/src/scripts/Biome.js
cp src/Chunk.js $WEB_VERSION_FILEPATH/src/scripts/Chunk.js
cp src/Grid.js $WEB_VERSION_FILEPATH/src/scripts/Grid.js
cp src/Ornamenter.js $WEB_VERSION_FILEPATH/src/scripts/Ornamenter.js
cp src/Pattern.js $WEB_VERSION_FILEPATH/src/scripts/Pattern.js
cp src/Perlin.js $WEB_VERSION_FILEPATH/src/scripts/Perlin.js
cp src/Rangerray.js $WEB_VERSION_FILEPATH/src/scripts/Rangerray.js
cp src/Renderer.js $WEB_VERSION_FILEPATH/src/scripts/Renderer.js
cp src/SubBiome.js $WEB_VERSION_FILEPATH/src/scripts/SubBiome.js
cp src/World.js $WEB_VERSION_FILEPATH/src/scripts/World.js
cp src/SystemRenderer.js $WEB_VERSION_FILEPATH/src/scripts/SystemRenderer.js

cp src/types.js $WEB_VERSION_FILEPATH/src/scripts/types.js
cp src/functions.js $WEB_VERSION_FILEPATH/src/scripts/functions.js
cp src/constants.js $WEB_VERSION_FILEPATH/src/scripts/constants.js
cp src/browser_script.js $WEB_VERSION_FILEPATH/src/scripts/env_script.js
cp src/issue_checking.js $WEB_VERSION_FILEPATH/src/scripts/issue_checking.js
cp src/sanitisation.js $WEB_VERSION_FILEPATH/src/scripts/sanitisation.js
cp src/validation.js $WEB_VERSION_FILEPATH/src/scripts/validation.js

echo Copied NarGen source to $WEB_VERSION_FILEPATH
